kind: pipeline
name: build-and-test-amd64

platform:
  os: linux
  arch: arm64

steps:
- name: Build, run
  image: ubuntu:19.10
  commands:
    - apt update -y
    - export DEBIAN_FRONTEND=noninteractive DEBCONF_NONINTERACTIVE_SEEN=true
    - apt-get install -y tzdata
    - apt-get install -y make gcc g++ cmake perl
    - apt-get install -y libboost-all-dev libboost-test-dev
    - apt-get install -y python3-matplotlib python3-numpy 
    - cmake .
    - make -j$(nproc)
    - ./genrandspec
    - ./findncopy -i rand_spectra -o selected -n data/star_list.txt -e sky
    - ./threshold -i selected -o spectra -t 1
    - ./trim -l 4700 -u 4800 -i rand_spectra -o spectra_trimmed
    - ./der_snr -d rand_spectra -o all_snr.csv
    - ./der_snr -d spectra -o selected_snr.csv
    - ./der_snr -f rand_spectra/0/0.dat
    - ./shift  -v 1.0e5 -i rand_spectra
    - ./marker -v -i rand_spectra/0/0.dat -i rand_spectra/0/1.dat -l 0.dat -l 1.dat  -t Spectra -l "Spectrum 1" -l "Spectrum 2" --elemlist data/line.list --shift 0.1 


- name: Unit tests
  image: ubuntu:19.10
  commands:
    - apt update -y
    - apt-get install -y libboost-all-dev
    - BOOST_TEST_LOG_LEVEL="all"  ./test_marker
  
