kind: pipeline
name: build-and-test-amd64

platform:
  os: linux
  arch: arm64

steps:
- name: Build and Test
  image: ubuntu:19.04
  commands:
    - apt-get update -y
    - apt-get install -y make gcc g++ cmake perl libboost-all-dev
    - cmake .
    - make -j$(nproc)
    - ./genrandspec
    - ./findncopy -i rand_spectra -o selected -n star_list.txt -e sky
    - ./threshold -i selected -o spectra -t 1
    - ./trim -l 4700 -u 4800 -i rand_spectra -o spectra_trimmed
    - ./der_snr -d rand_spectra -o all_snr.csv
    - ./der_snr -d spectra -o selected_snr.csv
    - ./shift  -v 1.0e5 -i rand_spectra

