language: cpp
compiler: gcc
os: linux 
arch: amd64 
dist: bionic
env:
    - CXX_STANDARD=c++17
addons:
  apt:
    packages:
        - g++-7
        - libboost-all-dev
        - cmake-data
        - cmake
            
script:
    - cmake .
    - make
    
after_success:
    - ./findncopy -i data -o selected -n star_list.txt -e sky
    - ./threshold -i selected -o spectra -t 1
    - ./trim -l 4700 -u 4800 -i data -o spectra_trimmed
    - ./der_snr -d data -o all_snr.csv
    - ./der_snr -d spectra -o selected_snr.csv
    - ./shift -h

branches:
  only:
      - master
notifications:
  email: false

      
