name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: upgrade
      run: sudo apt update; sudo apt install -y tzdata gcc g++ cmake doxygen doxygen-latex 
    - name: install boost
      run: sudo apt install -y libboost-all-dev libboost-test-dev
    - name: install py
      run: sudo apt install -y python3-matplotlib python3-numpy 
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
    - name: doxygen
      run: cd doc; doxygen Doxyfile; cd latex; make;
    - name: git conf
      run: git config --global user.name "a-lemonnier"; git remote set-url origin https://a-lemonnier:${{ secrets.pass }}@github.com/a-lemonnier/crappy-code-covid.git
    - name: push
      run: git add doc/latex/refman.pdf; git commit -m "CI Update"; git push

