name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: upgrade
      run: sudo apt update; sudo apt install -y tzdata gcc g++ clang cmake doxygen doxygen-latex graphviz
    - name: install boost
      run: sudo apt install -y libboost-all-dev libboost-test-dev
    - name: install py
      run: sudo apt install -y python3-matplotlib python3-numpy 
    - name: install ccfits
      run: sudo apt-get install -y libcfitsio-dev libccfits-dev 
    - name: install eigen3
      run: sudo apt-get install -y libeigen3-dev
    - name: install libnotify
      run: sudo apt-get install -y libgtk-3-dev libgdk-pixbuf2.0-0 libgtk2.0-dev libgdk-pixbuf2.0-dev libglib2.0-dev libnotify-dev
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
    - name: doxygen
      run: cd doc; doxygen Doxyfile; cd latex; make;
    - name: git conf
      run: git config --global user.name "a-lemonnier"; git remote set-url origin https://a-lemonnier:${{ secrets.pass }}@github.com/a-lemonnier/spec_tools.git
    - name: push
      run: git add doc/latex/refman.pdf; git commit -m "CI Update"; git push

