name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: update and upgarde
      run: apt update; apt upgrade -y; apt install - y tzdata make gcc g++ cmake perl
    - name: install boost
      run: apt install -y libboost-all-dev libboost-test-dev
    - name: install py
    - run: apt-get install -y python3-matplotlib python3-numpy 
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Werror" ..
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest

